LogisticSolutions/Controllers/CourierController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogisticSolutions.Interfaces;
using LogisticSolutions.Models;

namespace LogisticSolutions.Controllers
{
    public class CourierController : Controller
    {
        private readonly ICourierService _courierService;

        public CourierController(ICourierService courierService)
        {
            _courierService = courierService;
        }

        // GET: Courier
        [Authorize(Roles = "Courier, Admin")]
        public ActionResult GetReceipts()
        {
            var receipts = _courierService.GetReceipts();

            return View(receipts);
        }

        // GET: Courier
        [Authorize(Roles = "Courier, Admin")]
        public ActionResult GetDeliveries()
        {
            var receipts = _courierService.GetDeliveries();

            return View(receipts);
        }

        [Authorize(Roles = "Courier, Admin")]
        [HttpPost]
        public ActionResult Receipt(string deliveryId)
        {
            var result = _courierService.Reciept(deliveryId) ? "Odbior zrobiony!" : "Bład w obiorze";

            return Content(result);
        }

        [Authorize(Roles = "Courier, Admin")]
        [HttpPost]
        public ActionResult PassToWarehouse(string deliveryId)
        {
            var result = _courierService.WarehousePass(deliveryId) ? "Przekazanie na magazyn udane!" : "Bład w przekazaniu na magazyn";

            return Content(result);
        }

        [Authorize(Roles = "Courier, Admin")]
        [HttpPost]
        public ActionResult PickFromWarehouse(string deliveryId)
        {

            var result = _courierService.WarehousePick(deliveryId) ? "Pobrano przesyłkę z magazynu!" : "Bład w pobraniu przesyłki z magazynu";

            return Content(result);
        }

        [Authorize(Roles = "Courier, Admin")]
        [HttpPost]
        public ActionResult Deliver(string deliveryId)
        {
            var result = _courierService.Deliver(deliveryId) ? "Pobrano przesyłkę z magazynu!" : "Bład w pobraniu przesyłki z magazynu";

            return Content(result);
        }
        

    }
}

LogisticSolutions/Controllers/DeliveryController.cs
using System.Web.Mvc;
using LogisticSolutions.Interfaces;
using LogisticSolutions.Models;

namespace LogisticSolutions.Controllers
{
    public class DeliveryController : Controller
    {
        private readonly IDeliveryService _deliveryService;

        public DeliveryController(IDeliveryService deliveryService)
        {
            _deliveryService = deliveryService;
        }

        [Authorize(Roles = "Customer,Courier,Warehouseman,Admin")]
        public ActionResult AddDelivery()
        {
            return View();
        }


        [Authorize(Roles = "Customer,Admin")]
        [HttpPost]
        public ActionResult AddDelivery(AddDeliveryViewModel delivery)
        {

            if (ModelState.IsValid)
            {
                var result = _deliveryService.RegisterDelivery(delivery)
                    ? string.Format("Przesyłka zostanie odebrana z {0} oraz wysłana do {1}", delivery.PickupAddressCity,
                        delivery.DestinationAddressCity)
                    : "Błąd";

                return Content(result);    
            }

            return View(delivery);

        }

        public ActionResult Tracking()
        {
            var deliveries = _deliveryService.GetDeliveries();

            return View(deliveries);
        }


        public ActionResult TrackingDetails(string id)
        {
            var trackingDetails = _deliveryService.GetTrackingDetails(id);

            return View(trackingDetails);
        }
    }
}

LogisticSolutions/Controllers/TrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogisticSolutions.Models;

namespace LogisticSolutions.Controllers
{
    public class TrackingController : Controller
    {
        // GET: Tracking
        public ActionResult Index(string deliveryNumber)
        {

            var pickupAddress = new PostalAddress("Krzyżowa 22/1 42-123 Warszawa");
            var destinationAddress = new PostalAddress("Warszawska 31/2 43-122 Gdańsk");
            var delivery = new Delivery(pickupAddress, destinationAddress);

            delivery.AddTrackingPoint(TrackingStatusEnum.PickedUpFromSender);

            var deliveryTrackingHistory = delivery.TrackingHistory;

            return View(deliveryTrackingHistory);
        }
    }
}

LogisticSolutions/Controllers/WarehouseController.cs
using System.Web.Mvc;
using LogisticSolutions.Interfaces;

namespace LogisticSolutions.Controllers
{
    [Authorize(Roles = "Warehouseman,Admin")]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService _warehouseService;

        public WarehouseController(IWarehouseService warehouseService)
        {
            _warehouseService = warehouseService;
        }

        public ActionResult ShowWarehouse()
        {
            var deliveriesInWarehouse = _warehouseService.GetRecievedDeliveries();
            return View(deliveriesInWarehouse);
        }

        public ActionResult ShowPassed()
        {
            var passedDeliveries = _warehouseService.GetPassedDeliveries();
            return View(passedDeliveries);
        }

        public ActionResult WarehouseReceipt(string deliveryId)
        {
            var result = _warehouseService.WarehouseReceipt(deliveryId) ? string.Format("Przyjecie na magazyn przesylki {0}", deliveryId) :
            "Błąd w przyjęciu przesyłki na magazyn!";

            return Content(result);
        }

        public ActionResult WarehouseRelease(string deliveryId)
        {
            var result = _warehouseService.WarehouseRelease(deliveryId) ? string.Format("Wydanie z magazynu przesylki {0}", deliveryId) :
            "Błąd w wydaniu przesyłki z magazynu!";

            return Content(result);
        }
    }
}

LogisticSolutions/Views/Shared/CourierMenu.cshtml
<li>@Html.ActionLink("Wyświetl wszystkie odbiory", "GetReceipts", "Courier")</li>
<li>@Html.ActionLink("Odbierz od klienta", "Receipt", "Courier")</li>
<li>@Html.ActionLink("Zdaj na magazyn", "PassToWarehouse", "Courier")</li>
<li>@Html.ActionLink("Pobierz z magazynu", "PickFromWarehouse", "Courier")</li>

LogisticSolutions/Views/Shared/CustomerMenu.cshtml
<li>@Html.ActionLink("Zleć odbiór przesyłki", "AddDelivery", "Delivery")</li>
<li>@Html.ActionLink("Śledzenie przesyłki", "Tracking", "Delivery")</li>

LogisticSolutions/Views/Shared/WarehousemanMenu.cshtml
<li>@Html.ActionLink("Przyjęcie na magazyn", "ShowPassed", "Warehouse")</li>
<li>@Html.ActionLink("Wydanie z magazynu", "ShowWarehouse", "Warehouse")</li>

LogisticSolutions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Logistics Solutions</title>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300,300italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#">
                    Logistics Solutions
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.Partial("AdminMenu")
                        @Html.Partial("WarehousemanMenu")
                        @Html.Partial("CourierMenu")
                        @Html.Partial("CustomerMenu")
                    }
                    else if (User.IsInRole("Warehouseman"))
                    {
                        @Html.Partial("WarehousemanMenu")
                    }
                    else if (User.IsInRole("Courier"))
                    {
                        @Html.Partial("CourierMenu")
                    }
                    else if (User.IsInRole("Customer"))
                    {
                        @Html.Partial("CustomerMenu")
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>


    @RenderBody()
    <hr />
    <footer class="container">
        <p>&copy; @DateTime.Now.Year - Logistics Solutions</p>
    </footer>

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryuno")
    @RenderSection("scripts", required: false)
</body>
</html>